# Layer configuration for meta-flax
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "flax-layer"
BBFILE_PATTERN_flax-layer := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_flax-layer := "walnascar scarthgap"
